//Enigma rotor wiring from Wikipedia

#define R1 "EKMFLGDQVZNTOWYHXUSPAIBRCJ"
#define R2 "AJDKSIRUXBLHWTMCQGZNPYFVOE"
#define R3 "BDFHJLCPRTXVZNYEIWGAKMUSQO"
#define R4 "ESOVPZJAYQUIRHXLNFTGKDCMWB"
#define R5 "VZBRGITYUPSDNHLXAWMJQOFECK"
