//Enigma rotor wiring from Wikipedia

#define ROTOR1 "EKMFLGDQVZNTOWYHXUSPAIBRCJ"
#define ROTOR2 "AJDKSIRUXBLHWTMCQGZNPYFVOE"
#define ROTOR3 "BDFHJLCPRTXVZNYEIWGAKMUSQO"
#define ROTOR4 "ESOVPZJAYQUIRHXLNFTGKDCMWB"
#define ROTOR5 "VZBRGITYUPSDNHLXAWMJQOFECK"

//transparent rotor pass-through
#define ROTOR1_PT "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

//Enigma reflector wiring
#define UKW_A "EJMZALYXVBWFCRQUONTSPIKHGD"      
#define UKW_B "YRUHQSLDPXNGOKMIEBFZCWVJAT"       
#define UKW_C "FVPJIAOYEDRZXWGCTKUQSBNMHL"
